services:
  postgresql:
    container_name: postgresql-techeervent
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - techeervent-db:/techeervent-db/postgres-data
    ports:
      - '5432:5432'
    networks:
      - techeervent

  nest:
    container_name: nest-techeervent
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SWAGGER_URL=${SWAGGER_URL}
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
      - ODDS_OF_WINNING=${ODDS_OF_WINNING}
      - DAILY_OF_WINNING=${DAILY_OF_WINNING}
    ports:
      - '8000:8000'
    depends_on:
      - postgresql
    networks:
      - techeervent

networks:
  techeervent:
    driver: bridge

volumes:
  techeervent-db: